[package]
name = "tdlib-nif"
version = "0.1.0"
authors = ["Alexander Q <qalexx@gmail.com>"]

[lib]
name = "tdlib_nif"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.18.0"
rustler_codegen = "0.18.0"
lazy_static = "1.1.0"
rust-tdlib = { git = "https://github.com/lattenwald/rust-tdlib.git" }